// Vue-version/vue-project/src/views/Dashboard.vue
<template>
  <div class="relative min-h-screen overflow-hidden bg-gray-50">
    <!-- Grid background -->
    <div
      class="absolute inset-0 bg-[linear-gradient(to_right,rgba(0,0,0,0.03)_1px,transparent_1px),linear-gradient(to_bottom,rgba(0,0,0,0.03)_1px,transparent_1px)] bg-[size:32px_32px] pointer-events-none"
    />

    <!-- Navbar -->
    <header
      class="sticky top-0 backdrop-blur-md bg-white/80 border-b border-white/20 shadow-sm z-10"
    >
      <Navbar />
    </header>

    <!-- Dashboard Content -->
    <main class="relative max-w-[1200px] mx-auto px-6 py-12 z-10">
      <div class="flex justify-between items-center mb-10">
        <h2 class="text-3xl font-bold text-gray-800">Dashboard Overview 📊</h2>
        <button
          @click="isTicketModalOpen = true"
          class="bg-blue-600 text-white px-6 py-3 rounded-2xl shadow-lg hover:bg-blue-700 transition whitespace-nowrap"
        >
          Create Ticket
        </button>
      </div>

      <!-- Stats Grid -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
        <div
          v-for="(card, i) in statsCards"
          :key="i"
          class="bg-white/70 backdrop-blur-lg border border-white/30 rounded-2xl shadow-lg p-8 hover:-translate-y-1 hover:shadow-xl transition-all"
        >
          <p class="text-gray-500 text-sm tracking-wide mb-2">{{ card.label }}</p>
          <h3 class="text-4xl font-extrabold text-gray-700">
            {{ card.value }}
          </h3>
        </div>
      </div>

      <!-- Charts -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-10">
        <!-- Bar Chart -->
        <div
          class="bg-white/80 backdrop-blur-lg border border-white/40 rounded-2xl shadow-lg p-6 hover:shadow-xl transition-all"
        >
          <h3 class="text-lg font-semibold text-gray-800 mb-6">Ticket Summary</h3>
          <ApexChart
            width="100%"
            height="300"
            type="bar"
            :options="barOptions"
            :series="barSeries"
          />
        </div>

        <!-- Pie Chart -->
        <div
          class="bg-white/80 backdrop-blur-lg border border-white/40 rounded-2xl shadow-lg p-6 hover:shadow-xl transition-all"
        >
          <h3 class="text-lg font-semibold text-gray-800 mb-6">Ticket Distribution</h3>
          <ApexChart
            width="100%"
            height="300"
            type="pie"
            :options="pieOptions"
            :series="pieSeries"
          />
        </div>
      </div>

      <!-- Recent Activity -->
      <div class="mt-20">
        <p v-if="tickets.length" class="text-lg font-semibold text-gray-800 mb-6">
          Recent Activity
        </p>
        <TicketList v-if="tickets.length" />
      </div>
    </main>

    <!-- Ticket Modal -->
    <div
      v-if="isTicketModalOpen"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-50"
    >
      <div class="bg-white/90 backdrop-blur-sm rounded-2xl w-full max-w-lg p-6 relative">
        <button
          @click="isTicketModalOpen = false"
          class="absolute top-4 right-4 text-gray-500 hover:text-gray-700 text-xl font-bold"
        >
          ✕
        </button>
        <Tickets :isModal="true" />
      </div>
    </div>

    <!-- Footer -->
    <footer
      class="bg-white/80 backdrop-blur-sm border-t border-white/30 mt-16 text-center py-5 text-gray-600 text-sm"
    >
      © {{ new Date().getFullYear() }} Ticket Manager — All rights reserved.
    </footer>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue'
import ApexChart from 'vue3-apexcharts'
import Navbar from '../components/Navbar.vue'
import Tickets from '../components/Tickets.vue'
import TicketList from '../components/TicektList.vue'
import { useTicketStore } from '../stores/TicketContext'

// State from composable
const { tickets, setTickets } = useTicketStore()
const isTicketModalOpen = ref(false)

// Fetch tickets from localStorage
onMounted(() => {
  const storedTickets = JSON.parse(localStorage.getItem('ticketapp_tickets')) || []
  setTickets(storedTickets)
})

const total = computed(() => tickets.value.length)
const open = computed(() => tickets.value.filter((t) => t.status === 'open').length)
const resolved = computed(() => tickets.value.filter((t) => t.status === 'closed').length)

const statsCards = computed(() => [
  { label: 'Total Tickets', value: total.value },
  { label: 'Open Tickets', value: open.value },
  { label: 'Resolved Tickets', value: resolved.value },
])

// ApexCharts Data
const barOptions = {
  chart: { toolbar: { show: false } },
  xaxis: { categories: ['Open', 'Resolved'] },
  colors: ['#3b82f6', '#22c55e'],
  dataLabels: { enabled: true },
  plotOptions: {
    bar: {
      borderRadius: 6,
      columnWidth: '45%',
      distributed: true,
    },
  },
}

const barSeries = computed(() => [
  {
    name: 'Tickets',
    data: [open.value, resolved.value],
  },
])

const pieOptions = {
  labels: ['Open', 'Resolved'],
  colors: ['#3b82f6', '#22c55e'],
  legend: { position: 'bottom' },
}

const pieSeries = computed(() => [open.value, resolved.value])
</script>

<style scoped></style>

// React-version/src/pages/Dashboard.jsx
import { useEffect } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";
import { useTicket } from "../context/TicketContext";
import Tickets from "../components/Tickets";
import TicketList from "../components/TicektList";
import Navbar from "../components/Navbar";

export default function Dashboard() {
  const { tickets, setTickets, isTicketModalOpen, setIsTicketModalOpen } =
    useTicket();

  useEffect(() => {
    const storedTickets =
      JSON.parse(localStorage.getItem("ticketapp_tickets")) || [];
    setTickets(storedTickets);
  }, [setTickets]);

  const total = tickets.length;
  const open = tickets.filter((t) => t.status === "open").length;
  const resolved = tickets.filter((t) => t.status === "closed").length;

  const data = [
    { name: "Open", value: open },
    { name: "Resolved", value: resolved },
  ];

  const COLORS = ["#3b82f6", "#22c55e"];

  return (
    <div className="relative min-h-screen overflow-hidden bg-gray-50">
      {/* Grid background */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,rgba(0,0,0,0.03)_1px,transparent_1px),linear-gradient(to_bottom,rgba(0,0,0,0.03)_1px,transparent_1px)] bg-[size:32px_32px] pointer-events-none" />

      {/* Navbar */}
      <header className="sticky top-0 backdrop-blur-md bg-white/80 border-b border-white/20 shadow-sm z-10">
        <Navbar />
      </header>

      {/* Dashboard Content */}
      <main className="relative max-w-[1200px] mx-auto px-6 py-12 z-10">
        <div className="flex justify-between items-center mb-10">
          <h2 className="text-3xl font-bold text-gray-800">
            Dashboard Overview 📊
          </h2>
          <button
            onClick={() => setIsTicketModalOpen(true)}
            className="bg-blue-600 text-white px-6 py-3 rounded-2xl shadow-lg hover:bg-blue-700 transition whitespace-nowrap"
          >
            Create Ticket
          </button>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          {[
            {
              label: "Total Tickets",
              value: total,
              color: "from-blue-500 to-indigo-500",
            },
            {
              label: "Open Tickets",
              value: open,
              color: "from-yellow-400 to-orange-500",
            },
            {
              label: "Resolved Tickets",
              value: resolved,
              color: "from-green-400 to-emerald-600",
            },
          ].map((card, i) => (
            <div
              key={i}
              className="bg-white/70 backdrop-blur-lg border border-white/30 rounded-2xl shadow-lg p-8 hover:-translate-y-1 hover:shadow-xl transition-all"
            >
              <p className="text-gray-500 text-sm tracking-wide mb-2">
                {card.label}
              </p>
              <h3
                className={`text-4xl font-extrabold bg-gradient-to-r text-gray-700 bg-clip-text`}
              >
                {card.value}
              </h3>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
          {/* Bar Chart */}
          <div className="bg-white/80 backdrop-blur-lg border border-white/40 rounded-2xl shadow-lg p-6 hover:shadow-xl transition-all">
            <h3 className="text-lg font-semibold text-gray-800 mb-6">
              Ticket Summary
            </h3>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={data}>
                <XAxis dataKey="name" tick={{ fill: "#6b7280" }} />
                <YAxis tick={{ fill: "#6b7280" }} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "white",
                    borderRadius: "8px",
                    border: "1px solid #e5e7eb",
                  }}
                />
                <Bar dataKey="value" radius={[8, 8, 0, 0]}>
                  {data.map((entry, index) => (
                    <Cell key={index} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Pie Chart */}
          <div className="bg-white/80 backdrop-blur-lg border border-white/40 rounded-2xl shadow-lg p-6 hover:shadow-xl transition-all">
            <h3 className="text-lg font-semibold text-gray-800 mb-6">
              Ticket Distribution
            </h3>
            <ResponsiveContainer width="100%" height={300}>
              <PieChart>
                <Pie
                  data={data}
                  cx="50%"
                  cy="50%"
                  outerRadius={90}
                  fill="#8884d8"
                  dataKey="value"
                  label={({ name, value }) => `${name} (${value})`}
                >
                  {data.map((entry, index) => (
                    <Cell key={index} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Legend />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "white",
                    borderRadius: "8px",
                    border: "1px solid #e5e7eb",
                  }}
                />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="mt-20">
          {tickets.length ? (
            <p className="text-lg font-semibold text-gray-800 mb-6">
              Recent Activity
            </p>
          ) : (
            ""
          )}

          <TicketList />
        </div>
      </main>

      {/* Ticket Modal */}
      {isTicketModalOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white/90 backdrop-blur-sm rounded-2xl w-full max-w-lg p-6 relative">
            <button
              onClick={() => setIsTicketModalOpen(false)}
              className="absolute top-4 right-4 text-gray-500 hover:text-gray-700 text-xl font-bold"
            >
              ✕
            </button>
            <Tickets isModal={true} />
          </div>
        </div>
      )}

      <footer className="bg-white/80 backdrop-blur-sm border-t border-white/30 mt-16">
        <div className="max-w-[1200px] mx-auto text-center py-5 text-gray-600 text-sm">
          © {new Date().getFullYear()} Ticket Manager — All rights reserved.
        </div>
      </footer>
    </div>
  );
}
